import * as module from "../types/types";
const getApiClientsNonBoss = async () => {};
  const getApiClientsNonBossClientId = async () => {};
  const getApiClientsBoss = async () => {};
  const getApiClientsBossClientId = async () => {};
  const getApiClientsBossClientIdShares = async () => {};
  const getApiClientsBossStatuses = async () => {};
  const getApiClientsBossClientIdContacts = async () => {};
  const getApiClientsBossClientIdMeetings = async () => {};
  const getApiClientsBossClientIdQuotes = async () => {};
  const getApiContactsContactId = async () => {};
  const getApiContacts = async () => {};
  const getApiContactsAvailableformeeting = async () => {};
  const getApiMeetings = async () => {};
  const getApiMeetingsMeetingId = async () => {};
  const getApiMeetingsDateproperties = async () => {};
  const getApiMeetingsMeetingIdKeypersons = async () => {};
  const getApiMeetingsMeetingIdKeypersonsContactbased{meetingContactId} = async () => {};
  const getApiMeetingsMeetingIdKeypersons{meetingPersonId} = async () => {};
  const getApiMeetingsMeetingIdDocuments = async () => {};
  const getApiMeetingsMeetingIdAgenda = async () => {};
  const getApiQuotes = async () => {};
  const getApiQuotesQuoteId = async () => {};
  const getApiUsers = async () => {};
  const getApiVenues = async () => {};
  const getApiVenuesVenueId = async () => {};
  